server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5433/futuWisedb?currentSchema=cursospython
spring.datasource.username=postgres
spring.datasource.password=post
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.default_schema=cursospython
jwt.secret=Q2hhbmdlVGhpc1RvU29tZVN1cGVyU2VjdXJlU3RyaW5nMTIzIT8kKiYoKQ==
